version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: ./src/infra/docker/app/Dockerfile
    depends_on:
      postgres:
        condition: service_started

    container_name: 'app'
    network_mode: 'host'
    volumes:
      - .:/usr/dev
  postgres:
    image: postgres:latest
    container_name: 'app-postgres'
    network_mode: 'host'
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
    volumes:
    - postgres:/var/lib/postgresql/data
  
volumes:
  postgres:
    driver: local